#!/usr/bin/env python3
"""
Aspero Amplitude → Slack Agent
================================
Fetches 7-day rolling signup funnel data from Amplitude and posts a
narrative report to Slack generated by Claude (LLM).

Report flow:
  1. Python fetches all Amplitude data (Funnel API + Segmentation API)
  2. Python computes derived metrics (WoW deltas, device tier classification,
     Em%, PIN%, SSO adoption %, etc.)
  3. Python pre-formats the device tier table (monospace code block)
  4. Executive briefing posted first (pure Python, always available):
     ~18 lines, verdict-first, for CEO/CPO/CMO
  5. Detailed report posted second:
     a. Claude via AWS Bedrock generates narrative report (if AWS creds set)
     b. Fallback: Block Kit format via build_message_v2() if no AWS creds

Funnel milestones:
  OTP          = VERIFY_OTP_SUCCESS           (new + returning users)
  Email Page   = EMAIL_PAGE_VIEW              (proxy for new-user OTPs at 99.5%)
  Email ✓ OTP  = EMAIL_VERIFY_OTP_SUCCESS     (new users only)
  Email ✓ SSO  = SSO_VERIFICATION_SUCCESS     (new users only, launched 6 Mar 2026)
  Signup ✓     = SETUP_SECURE_PIN_SUCCESS     (new users only)

API calls: 12 total
  [1–2]  Device funnel: OTP→EmailPage→Email→Signup, OTP→EmailPage→SSO→Signup (current 7d)
  [3–6]  Event totals for prior 7d (WoW comparison)
  [7–8]  Event totals for prior-prior 7d (consecutive trend detection)
  [9–12] Event totals for yesterday (daily snapshot)

Usage:
  python3 agent.py [--dry-run]

Required env vars:
  AMPLITUDE_API_KEY      Amplitude API key (Project 506002)
  AMPLITUDE_SECRET_KEY   Amplitude secret key
  SLACK_WEBHOOK_URL      Slack incoming webhook URL
  AWS_ACCESS_KEY_ID      AWS key for Bedrock/Claude (optional — falls back to Block Kit)
"""

import json
import os
import sys
from datetime import datetime, timedelta

from amplitude import AmplitudeClient
from config import MILESTONE_EVENTS, KYC_EVENTS, KYC_FUNNEL_V2_DATE
from insights import (
    compute_device_funnel_table,
    compute_wow_totals,
    compute_yesterday_snapshot,
    generate_alerts_v2,
    generate_wins_v2,
    get_overall_health_v2,
)
from slack import build_exec_report, build_message_v2, send_to_slack


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _date_window(days: int, offset_days: int = 0):
    end   = datetime.now() - timedelta(days=offset_days)
    start = end - timedelta(days=days)
    return start.strftime("%Y%m%d"), end.strftime("%Y%m%d")


def _period_label(start_str: str, end_str: str) -> str:
    start = datetime.strptime(start_str, "%Y%m%d")
    end   = datetime.strptime(end_str,   "%Y%m%d")
    if start.year == end.year:
        return f"{start.strftime('%b %-d')} – {end.strftime('%-d, %Y')}"
    return f"{start.strftime('%b %-d, %Y')} – {end.strftime('%b %-d, %Y')}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(dry_run: bool = False):
    # ── Credentials ───────────────────────────────────────────────────────
    api_key          = os.getenv("AMPLITUDE_API_KEY")
    secret_key       = os.getenv("AMPLITUDE_SECRET_KEY")
    webhook_url      = os.getenv("SLACK_WEBHOOK_URL")
    aws_key          = os.getenv("AWS_ACCESS_KEY_ID")

    missing = [k for k, v in {
        "AMPLITUDE_API_KEY":    api_key,
        "AMPLITUDE_SECRET_KEY": secret_key,
        "SLACK_WEBHOOK_URL":    webhook_url,
    }.items() if not v]

    if missing and not dry_run:
        print(f"❌  Missing env vars: {', '.join(missing)}")
        sys.exit(1)

    client = AmplitudeClient(api_key or "", secret_key or "")

    # ── Date windows ──────────────────────────────────────────────────────
    cur_start,        cur_end        = _date_window(7)
    prev_start,       prev_end       = _date_window(7, offset_days=7)
    prev_prev_start,  prev_prev_end  = _date_window(7, offset_days=14)
    yest_str                         = (datetime.now() - timedelta(days=1)).strftime("%Y%m%d")
    label = _period_label(cur_start, cur_end)

    print(f"\n🗓  Period:          {label}  ({cur_start} → {cur_end})")
    print(f"📅  Prior period:    {prev_start} → {prev_end}")
    print(f"📅  Prior-prior:     {prev_prev_start} → {prev_prev_end}")
    print(f"📅  Yesterday:       {yest_str}")

    # ── Fetch [1–2] — current 7d funnels by device type ──────────────────
    # device_type is the correct Amplitude Funnel API group_by parameter.
    # device_family is shown in the Amplitude UI but returns empty data from
    # the Funnel API. classify_device_type() handles both marketing names
    # and raw hardware codes (SM-S901B, 2201116TG, RMX3511).
    print("\n📡  [1/12] OTP → Email Page → Email OTP → Signup funnel by device type...")
    otp_email_funnel = client.get_funnel_by_device_type(
        [MILESTONE_EVENTS["otp"], MILESTONE_EVENTS["email_page"],
         MILESTONE_EVENTS["email_otp"], MILESTONE_EVENTS["signup"]],
        cur_start, cur_end,
    )
    print(f"    device_types={len(otp_email_funnel)}")

    print("\n📡  [2/12] OTP → Email Page → Email SSO → Signup funnel by device type...")
    otp_sso_funnel = client.get_funnel_by_device_type(
        [MILESTONE_EVENTS["otp"], MILESTONE_EVENTS["email_page"],
         MILESTONE_EVENTS["email_sso"], MILESTONE_EVENTS["signup"]],
        cur_start, cur_end,
    )
    print(f"    device_types={len(otp_sso_funnel)}")

    # ── Fetch [3–6] — prior 7d totals (WoW) ──────────────────────────────
    print(f"\n📡  [3–6] Prior 7d totals ({prev_start} → {prev_end})...")
    prior_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],       prev_start, prev_end)
    prior_email  = client.get_event_totals(MILESTONE_EVENTS["email_otp"], prev_start, prev_end)
    prior_sso    = client.get_event_totals(MILESTONE_EVENTS["email_sso"], prev_start, prev_end)
    prior_signup = client.get_event_totals(MILESTONE_EVENTS["signup"],    prev_start, prev_end)
    print(f"    otp={prior_otp:,}  email_otp={prior_email:,}  email_sso={prior_sso:,}  signup={prior_signup:,}")

    # ── Fetch [7–8] — prior-prior 7d totals (consecutive trend) ──────────
    print(f"\n📡  [7–8] Prior-prior 7d totals ({prev_prev_start} → {prev_prev_end})...")
    prev_prev_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],    prev_prev_start, prev_prev_end)
    prev_prev_signup = client.get_event_totals(MILESTONE_EVENTS["signup"], prev_prev_start, prev_prev_end)
    print(f"    otp={prev_prev_otp:,}  signup={prev_prev_signup:,}")

    # ── Fetch [9–12] — yesterday snapshot ────────────────────────────────
    print(f"\n📡  [9–12] Yesterday totals ({yest_str})...")
    yest_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],       yest_str, yest_str)
    yest_email  = client.get_event_totals(MILESTONE_EVENTS["email_otp"], yest_str, yest_str)
    yest_sso    = client.get_event_totals(MILESTONE_EVENTS["email_sso"], yest_str, yest_str)
    yest_signup = client.get_event_totals(MILESTONE_EVENTS["signup"],    yest_str, yest_str)
    print(f"    otp={yest_otp:,}  email={yest_email:,}  sso={yest_sso:,}  signup={yest_signup:,}")

    # ── Fetch [13–16] — KYC funnel (7-day cohort offset window) ──────────
    # Offset window: signups 8–14d ago (cohort) → KYC completions 1–7d ago.
    # This gives each cohort exactly 7 days to complete KYC.
    # prior_signup (already fetched above) is the cohort denominator.
    print(f"\n📡  [13–16] KYC funnel (cohort {prev_start}→{prev_end}, completions {cur_start}→{cur_end})...")
    kyc_cohort_starts       = client.get_event_totals(KYC_EVENTS["kyc_start"],    prev_start,      prev_end)
    kyc_cur_completions     = client.get_event_totals(KYC_EVENTS["kyc_complete"], cur_start,       cur_end)
    kyc_prior_cohort_starts = client.get_event_totals(KYC_EVENTS["kyc_start"],    prev_prev_start, prev_prev_end)
    kyc_prior_completions   = client.get_event_totals(KYC_EVENTS["kyc_complete"], prev_start,      prev_end)
    print(f"    cohort_starts={kyc_cohort_starts:,}  cur_done={kyc_cur_completions:,}  "
          f"prior_cohort_starts={kyc_prior_cohort_starts:,}  prior_done={kyc_prior_completions:,}")

    # ── Fetch [17–18] — KYC by device type (rolling 7d, for tier table) ──
    # Rolling same window as signup device table — used for relative tier
    # comparison only, not the headline cohort metric.
    print(f"\n📡  [17–18] KYC by device type (rolling {cur_start}→{cur_end})...")
    kyc_starts_by_device = client.get_event_by_device_type(KYC_EVENTS["kyc_start"],    cur_start, cur_end)
    kyc_done_by_device   = client.get_event_by_device_type(KYC_EVENTS["kyc_complete"], cur_start, cur_end)
    print(f"    kyc_start_devices={len(kyc_starts_by_device)}  kyc_done_devices={len(kyc_done_by_device)}")

    # ── Compute metrics ───────────────────────────────────────────────────
    print("\n🔍  Computing metrics...")

    device_table = compute_device_funnel_table(otp_email_funnel, otp_sso_funnel)

    cur_otp         = sum(s[0] for s in otp_email_funnel.values() if s)
    cur_email_page  = sum(s[1] for s in otp_email_funnel.values() if len(s) > 1)
    cur_email       = sum(s[2] for s in otp_email_funnel.values() if len(s) > 2)
    cur_sso         = sum(s[2] for s in otp_sso_funnel.values()   if len(s) > 2)
    cur_signup      = (sum(s[3] for s in otp_email_funnel.values() if len(s) > 3) +
                       sum(s[3] for s in otp_sso_funnel.values()   if len(s) > 3))
    cur_email_total = cur_email + cur_sso

    prior_email_total = prior_email + prior_sso

    wow = compute_wow_totals(
        cur_otp, cur_email_total, cur_signup,
        prior_otp, prior_email_total, prior_signup,
    )

    yesterday_snapshot = compute_yesterday_snapshot(
        yest_otp, yest_email + yest_sso, yest_signup,
        cur_otp, cur_email_total, cur_signup,
    )

    sso_pct   = round(cur_sso   / cur_email_total * 100, 1) if cur_email_total > 0 else 0.0
    email_pct = round(cur_email / cur_email_total * 100, 1) if cur_email_total > 0 else 0.0

    health = get_overall_health_v2(wow, device_table)
    alerts = generate_alerts_v2(wow, device_table, sso_pct)
    wins   = generate_wins_v2(wow, device_table, sso_pct)

    from datetime import date
    from config import SSO_LAUNCH_DATE
    days_since_sso = (date.today() - SSO_LAUNCH_DATE).days
    days_remaining = max(0, 30 - days_since_sso)

    # KYC metrics — offset window cohort analysis
    kyc_start_pct       = round(kyc_cohort_starts       / prior_signup              * 100, 1) if prior_signup              > 0 else 0.0
    kyc_done_pct        = round(kyc_cur_completions      / kyc_cohort_starts         * 100, 1) if kyc_cohort_starts         > 0 else 0.0
    prior_kyc_start_pct = round(kyc_prior_cohort_starts  / prev_prev_signup          * 100, 1) if prev_prev_signup          > 0 else 0.0
    prior_kyc_done_pct  = round(kyc_prior_completions    / kyc_prior_cohort_starts   * 100, 1) if kyc_prior_cohort_starts   > 0 else 0.0
    kyc_start_wow_pp    = round(kyc_start_pct - prior_kyc_start_pct, 1)
    kyc_done_wow_pp     = round(kyc_done_pct  - prior_kyc_done_pct,  1)

    # Flag if current report period overlaps with the Mar 10 funnel change
    days_since_kyc_v2   = (date.today() - KYC_FUNNEL_V2_DATE).days
    kyc_v2_recent       = 0 <= days_since_kyc_v2 <= 14

    # KYC by device tier (rolling 7d) — for full funnel summary table
    from insights import classify_device_type
    from config import DEVICE_TIER_LABELS
    kyc_tier_starts: dict = {}
    kyc_tier_done:   dict = {}
    for device, count in kyc_starts_by_device.items():
        tier = classify_device_type(device)
        kyc_tier_starts[tier] = kyc_tier_starts.get(tier, 0) + count
    for device, count in kyc_done_by_device.items():
        tier = classify_device_type(device)
        kyc_tier_done[tier] = kyc_tier_done.get(tier, 0) + count

    # Build combined tier table: Em%, PIN%, KYC Start%, KYC Done% per tier
    kyc_tier_data = []
    for row in device_table:
        tier   = row["tier"]
        starts = kyc_tier_starts.get(tier, 0)
        done   = kyc_tier_done.get(tier, 0)
        ks_pct = round(starts / row["signup"] * 100, 1) if row["signup"] > 0 else 0.0
        kd_pct = round(done   / starts        * 100, 1) if starts        > 0 else 0.0
        kyc_tier_data.append({
            "label":     row["label"],
            "em_pct":    row["newuser_to_email_pct"],
            "pin_pct":   row["email_to_signup_pct"],
            "kyc_start": ks_pct,
            "kyc_done":  kd_pct,
        })

    print(f"\n  📊 Signups:        {cur_signup:,}")
    print(f"  📧 Email method:   OTP {email_pct}% | SSO {sso_pct}%")
    print(f"  🏦 KYC:            Start {kyc_start_pct}% ({kyc_start_wow_pp:+.1f}pp WoW) | Done {kyc_done_pct}% ({kyc_done_wow_pp:+.1f}pp WoW)")
    print(f"  🩺 Health:         {health.upper()}")

    # ── Pre-format device table ───────────────────────────────────────────
    from slack import _milestone_table
    device_table_formatted = _milestone_table(
        device_table, cur_email_page, cur_email_total, cur_signup
    )

    # ── Build data dict for LLM reporter ─────────────────────────────────
    now_ist = datetime.utcnow() + timedelta(hours=5, minutes=30)
    data = {
        "report_date":           now_ist.strftime("%a %b %-d, %Y"),
        "period":                label,
        "cur_signup":            cur_signup,
        "cur_otp":               cur_otp,
        "cur_email_total":       cur_email_total,
        "cur_email_page":        cur_email_page,
        "cur_sso":               cur_sso,
        "sso_pct":               sso_pct,
        "wow": {
            "signup": wow.get("signup", {}),
            "otp":    wow.get("otp",    {}),
            "email":  wow.get("email",  {}),
        },
        "prior_prior": {
            "signup": prev_prev_signup,
            "otp":    prev_prev_otp,
        },
        "yesterday": {
            "signup":     yesterday_snapshot.get("registrations", {}),
            "otp":        yesterday_snapshot.get("otp_verified",  {}),
            "email_conv": yesterday_snapshot.get("email_conv",    {}),
        },
        "device_table": [
            {
                "tier":     r["tier"],
                "label":    r["label"],
                "mob_verif": r["email_page"],
                "email":    r["email_total"],
                "signup":   r["signup"],
                "em_pct":   r["newuser_to_email_pct"],
                "pin_pct":  r["email_to_signup_pct"],
            }
            for r in device_table
        ],
        "device_table_formatted":  device_table_formatted,
        "sso_available":           days_since_sso >= 0,
        "days_since_sso":          days_since_sso,
        "days_remaining_sso":      days_remaining,
        "kyc": {
            "cohort_signups":       prior_signup,
            "cohort_starts":        kyc_cohort_starts,
            "cur_completions":      kyc_cur_completions,
            "start_pct":            kyc_start_pct,
            "done_pct":             kyc_done_pct,
            "start_wow_pp":         kyc_start_wow_pp,
            "done_wow_pp":          kyc_done_wow_pp,
            "v2_recent":            kyc_v2_recent,
            "days_since_v2":        days_since_kyc_v2,
        },
        "generated_at":            now_ist.strftime("%Y-%m-%d %H:%M"),
    }

    # ── Build executive briefing (pure Python — always available) ────────
    exec_payload = build_exec_report(
        period_label=label,
        cur_signup=cur_signup,
        wow=wow,
        prev_prev_signup=prev_prev_signup,
        yesterday_snapshot=yesterday_snapshot,
        device_table=device_table,
        sso_pct=sso_pct,
        kyc_start_pct=kyc_start_pct,
        kyc_done_pct=kyc_done_pct,
        kyc_start_wow_pp=kyc_start_wow_pp,
        kyc_done_wow_pp=kyc_done_wow_pp,
        kyc_cohort_signups=prior_signup,
        kyc_v2_recent=kyc_v2_recent,
        kyc_tier_data=kyc_tier_data,
        alerts=alerts,
        wins=wins,
        health=health,
        generated_at=now_ist.strftime("%Y-%m-%d %H:%M"),
    )

    # ── Build detailed report (LLM if available, Block Kit fallback) ──────
    if dry_run:
        print("\n── DRY RUN — executive briefing ─────────────────────────────────────")
        print(exec_payload["text"])
        print("\n── DRY RUN — data dict ──────────────────────────────────────────────")
        print(json.dumps(data, indent=2, ensure_ascii=False))
        print("────────────────────────────────────────────────────────────────────")
        return

    report_text = None
    if aws_key:
        try:
            print("\n🤖  Generating narrative report via Claude...")
            from reporter import generate_report
            report_text = generate_report(data)
            print("✅  LLM report generated.")
        except Exception as e:
            print(f"⚠️  LLM report failed ({e}), falling back to Block Kit format...")

    if report_text:
        detailed_payload = {"text": report_text}
    else:
        detailed_payload = build_message_v2(
            period_label=label,
            device_table=device_table,
            cur_otp=cur_otp,
            cur_email_page=cur_email_page,
            cur_email_otp=cur_email,
            cur_email_sso=cur_sso,
            cur_signup=cur_signup,
            wow=wow,
            yesterday_snapshot=yesterday_snapshot,
            alerts=alerts,
            wins=wins,
            health=health,
        )

    # ── Post: executive first, detailed second ────────────────────────────
    print("\n📤  Sending executive briefing to Slack...")
    if not send_to_slack(webhook_url, exec_payload):
        print("⚠️  Executive briefing failed to send — continuing with detailed report...")

    print("📤  Sending detailed report to Slack...")
    if send_to_slack(webhook_url, detailed_payload):
        print("✅  Reports sent!")
    else:
        print("❌  Failed to send detailed report to Slack")
        sys.exit(1)


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    run(dry_run=dry_run)
