#!/usr/bin/env python3
"""
Aspero Amplitude → Slack Agent
================================
Fetches 7-day rolling signup funnel data from Amplitude and posts a
narrative report to Slack generated by Claude (LLM).

Report flow:
  1. Python fetches all Amplitude data (Funnel API + Segmentation API)
  2. Python computes derived metrics (WoW deltas, device tier classification,
     Em%, PIN%, SSO adoption %, etc.)
  3. Python pre-formats the device tier table (monospace code block)
  4. Executive briefing posted to Slack (pure Python, always available):
     ~18 lines, verdict-first, for CEO/CPO/CMO

Funnel milestones:
  OTP          = VERIFY_OTP_SUCCESS           (new + returning users)
  Email Page   = EMAIL_PAGE_VIEW              (proxy for new-user OTPs at 99.5%)
  Email ✓ OTP  = EMAIL_VERIFY_OTP_SUCCESS     (new users only)
  Email ✓ SSO  = SSO_VERIFICATION_SUCCESS     (new users only, launched 6 Mar 2026)
  Signup ✓     = SETUP_SECURE_PIN_SUCCESS     (new users only)

API calls: 24 total
  [1–2]   Device funnel: OTP→EmailPage→Email→Signup, OTP→EmailPage→SSO→Signup (current 7d)
  [3–6]   Event totals for prior 7d (WoW comparison)
  [7–8]   Event totals for prior-prior 7d (consecutive trend detection)
  [9–12]  Event totals for yesterday (daily snapshot)
  [13–16] KYC cohort — start + complete × current + prior offset windows
  [17–24] KYC intermediate steps — 4 events × current + prior cohort windows

Usage:
  python3 agent.py [--dry-run]

Required env vars:
  AMPLITUDE_API_KEY      Amplitude API key (Project 506002)
  AMPLITUDE_SECRET_KEY   Amplitude secret key
  SLACK_WEBHOOK_URL      Slack incoming webhook URL
  AWS_ACCESS_KEY_ID      AWS key for Bedrock/Claude (optional — falls back to Block Kit)
"""

import os
import sys
from datetime import datetime, timedelta, date

from amplitude import AmplitudeClient
from config import MILESTONE_EVENTS, KYC_EVENTS, KYC_STEP_ORDER, KYC_FUNNEL_V2_DATE, SSO_LAUNCH_DATE
from insights import (
    compute_device_funnel_table,
    compute_wow_totals,
    compute_yesterday_snapshot,
    compute_kyc_steps_wow,
    generate_alerts_v2,
    generate_wins_v2,
    get_overall_health_v2,
)
from slack import build_exec_report, send_to_slack


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _date_window(days: int, offset_days: int = 0):
    end   = datetime.now() - timedelta(days=offset_days)
    start = end - timedelta(days=days)
    return start.strftime("%Y%m%d"), end.strftime("%Y%m%d")


def _period_label(start_str: str, end_str: str) -> str:
    start = datetime.strptime(start_str, "%Y%m%d")
    end   = datetime.strptime(end_str,   "%Y%m%d")
    if start.year == end.year:
        return f"{start.strftime('%b %-d')} – {end.strftime('%-d, %Y')}"
    return f"{start.strftime('%b %-d, %Y')} – {end.strftime('%b %-d, %Y')}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(dry_run: bool = False):
    # ── Credentials ───────────────────────────────────────────────────────
    api_key          = os.getenv("AMPLITUDE_API_KEY")
    secret_key       = os.getenv("AMPLITUDE_SECRET_KEY")
    webhook_url      = os.getenv("SLACK_WEBHOOK_URL")

    missing = [k for k, v in {
        "AMPLITUDE_API_KEY":    api_key,
        "AMPLITUDE_SECRET_KEY": secret_key,
        "SLACK_WEBHOOK_URL":    webhook_url,
    }.items() if not v]

    if missing and not dry_run:
        print(f"❌  Missing env vars: {', '.join(missing)}")
        sys.exit(1)

    client = AmplitudeClient(api_key or "", secret_key or "")

    # ── Date windows ──────────────────────────────────────────────────────
    cur_start,        cur_end        = _date_window(7)
    prev_start,       prev_end       = _date_window(7, offset_days=7)
    prev_prev_start,  prev_prev_end  = _date_window(7, offset_days=14)
    yest_str                         = (datetime.now() - timedelta(days=1)).strftime("%Y%m%d")
    label = _period_label(cur_start, cur_end)

    print(f"\n🗓  Period:          {label}  ({cur_start} → {cur_end})")
    print(f"📅  Prior period:    {prev_start} → {prev_end}")
    print(f"📅  Prior-prior:     {prev_prev_start} → {prev_prev_end}")
    print(f"📅  Yesterday:       {yest_str}")

    # ── Fetch [1–2] — current 7d funnels by device type ──────────────────
    # device_type is the correct Amplitude Funnel API group_by parameter.
    # device_family is shown in the Amplitude UI but returns empty data from
    # the Funnel API. classify_device_type() handles both marketing names
    # and raw hardware codes (SM-S901B, 2201116TG, RMX3511).
    print("\n📡  [1/24] OTP → Email Page → Email OTP → Signup funnel by device type...")
    otp_email_funnel = client.get_funnel_by_device_type(
        [MILESTONE_EVENTS["otp"], MILESTONE_EVENTS["email_page"],
         MILESTONE_EVENTS["email_otp"], MILESTONE_EVENTS["signup"]],
        cur_start, cur_end,
    )
    print(f"    device_types={len(otp_email_funnel)}")

    print("\n📡  [2/24] OTP → Email Page → Email SSO → Signup funnel by device type...")
    otp_sso_funnel = client.get_funnel_by_device_type(
        [MILESTONE_EVENTS["otp"], MILESTONE_EVENTS["email_page"],
         MILESTONE_EVENTS["email_sso"], MILESTONE_EVENTS["signup"]],
        cur_start, cur_end,
    )
    print(f"    device_types={len(otp_sso_funnel)}")

    # ── Fetch [3–6] — prior 7d totals (WoW) ──────────────────────────────
    print(f"\n📡  [3–6] Prior 7d totals ({prev_start} → {prev_end})...")
    prior_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],       prev_start, prev_end)
    prior_email  = client.get_event_totals(MILESTONE_EVENTS["email_otp"], prev_start, prev_end)
    prior_sso    = client.get_event_totals(MILESTONE_EVENTS["email_sso"], prev_start, prev_end)
    prior_signup = client.get_event_totals(MILESTONE_EVENTS["signup"],    prev_start, prev_end)
    print(f"    otp={prior_otp:,}  email_otp={prior_email:,}  email_sso={prior_sso:,}  signup={prior_signup:,}")

    # ── Fetch [7–8] — prior-prior 7d totals (consecutive trend) ──────────
    print(f"\n📡  [7–8] Prior-prior 7d totals ({prev_prev_start} → {prev_prev_end})...")
    prev_prev_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],    prev_prev_start, prev_prev_end)
    prev_prev_signup = client.get_event_totals(MILESTONE_EVENTS["signup"], prev_prev_start, prev_prev_end)
    print(f"    otp={prev_prev_otp:,}  signup={prev_prev_signup:,}")

    # ── Fetch [9–12] — yesterday snapshot ────────────────────────────────
    print(f"\n📡  [9–12] Yesterday totals ({yest_str})...")
    yest_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],       yest_str, yest_str)
    yest_email  = client.get_event_totals(MILESTONE_EVENTS["email_otp"], yest_str, yest_str)
    yest_sso    = client.get_event_totals(MILESTONE_EVENTS["email_sso"], yest_str, yest_str)
    yest_signup = client.get_event_totals(MILESTONE_EVENTS["signup"],    yest_str, yest_str)
    print(f"    otp={yest_otp:,}  email={yest_email:,}  sso={yest_sso:,}  signup={yest_signup:,}")

    # ── Fetch [13–16] — KYC headline (offset window cohort) ──────────────
    # KYC Start%:  RISKDETAILS_SUBMIT [8-14d ago] / Signups [8-14d ago]
    #              = "What % of last week's signups started KYC in the same week?"
    # KYC Done%:   READY_FOR_TRADE [1-7d ago] / RISKDETAILS_SUBMIT [8-14d ago]
    #              = "Of starters 8-14d ago, what % completed within 7 days?" (offset window)
    print(f"\n📡  [13–16] KYC headline (cohort {prev_start}→{prev_end}, completions {cur_start}→{cur_end})...")
    kyc_cohort_starts       = client.get_event_totals(KYC_EVENTS["kyc_start"],    prev_start,      prev_end)
    kyc_cur_completions     = client.get_event_totals(KYC_EVENTS["kyc_complete"], cur_start,       cur_end)
    kyc_prior_cohort_starts = client.get_event_totals(KYC_EVENTS["kyc_start"],    prev_prev_start, prev_prev_end)
    kyc_prior_completions   = client.get_event_totals(KYC_EVENTS["kyc_complete"], prev_start,      prev_end)
    print(f"    cohort_starts={kyc_cohort_starts:,}  cur_done={kyc_cur_completions:,}  "
          f"prior_cohort_starts={kyc_prior_cohort_starts:,}  prior_done={kyc_prior_completions:,}")

    # ── Fetch [17–24] — KYC intermediate steps (same-window WoW) ─────────
    # All intermediate steps use the same cohort window (prev/prev_prev).
    # Same-window (not offset) — these steps happen within days of signup.
    # WoW comparison identifies which specific step deteriorated.
    # kyc_wet_sig / kyc_demat are V2-only (post Mar 10); will return 0 for earlier windows.
    print(f"\n📡  [17–24] KYC intermediate steps (cur cohort {prev_start}→{prev_end}, "
          f"prior cohort {prev_prev_start}→{prev_prev_end})...")
    kyc_steps_cur  = {}
    kyc_steps_prev = {}
    for step_key in KYC_STEP_ORDER:
        event = KYC_EVENTS[step_key]
        kyc_steps_cur[step_key]  = client.get_event_totals(event, prev_start,      prev_end)
        kyc_steps_prev[step_key] = client.get_event_totals(event, prev_prev_start, prev_prev_end)
    print("    cur: " + "  ".join(f"{k}={v:,}" for k, v in kyc_steps_cur.items()))
    print("    prev:" + "  ".join(f"{k}={v:,}" for k, v in kyc_steps_prev.items()))

    # ── Compute metrics ───────────────────────────────────────────────────
    print("\n🔍  Computing metrics...")

    device_table = compute_device_funnel_table(otp_email_funnel, otp_sso_funnel)

    cur_otp         = sum(s[0] for s in otp_email_funnel.values() if s)
    cur_email_page  = sum(s[1] for s in otp_email_funnel.values() if len(s) > 1)
    cur_email       = sum(s[2] for s in otp_email_funnel.values() if len(s) > 2)
    cur_sso         = sum(s[2] for s in otp_sso_funnel.values()   if len(s) > 2)
    cur_signup      = (sum(s[3] for s in otp_email_funnel.values() if len(s) > 3) +
                       sum(s[3] for s in otp_sso_funnel.values()   if len(s) > 3))
    cur_email_total = cur_email + cur_sso

    prior_email_total = prior_email + prior_sso

    wow = compute_wow_totals(
        cur_otp, cur_email_total, cur_signup,
        prior_otp, prior_email_total, prior_signup,
    )

    yesterday_snapshot = compute_yesterday_snapshot(
        yest_otp, yest_email + yest_sso, yest_signup,
        cur_otp, cur_email_total, cur_signup,
    )

    sso_pct   = round(cur_sso   / cur_email_total * 100, 1) if cur_email_total > 0 else 0.0
    email_pct = round(cur_email / cur_email_total * 100, 1) if cur_email_total > 0 else 0.0

    # KYC headline metrics (offset window)
    kyc_start_pct       = round(kyc_cohort_starts       / prior_signup              * 100, 1) if prior_signup              > 0 else 0.0
    kyc_done_pct        = round(kyc_cur_completions      / kyc_cohort_starts         * 100, 1) if kyc_cohort_starts         > 0 else 0.0
    prior_kyc_start_pct = round(kyc_prior_cohort_starts  / prev_prev_signup          * 100, 1) if prev_prev_signup          > 0 else 0.0
    prior_kyc_done_pct  = round(kyc_prior_completions    / kyc_prior_cohort_starts   * 100, 1) if kyc_prior_cohort_starts   > 0 else 0.0
    kyc_start_wow_pp    = round(kyc_start_pct - prior_kyc_start_pct, 1)
    kyc_done_wow_pp     = round(kyc_done_pct  - prior_kyc_done_pct,  1)

    # KYC intermediate step WoW (same-window, denominator = signups)
    kyc_steps_wow = compute_kyc_steps_wow(
        cur_counts=kyc_steps_cur,
        prev_counts=kyc_steps_prev,
        cur_signups=prior_signup,
        prev_signups=prev_prev_signup,
    )

    # Flag if current report period overlaps with the Mar 10 funnel change
    days_since_kyc_v2 = (date.today() - KYC_FUNNEL_V2_DATE).days
    kyc_v2_recent     = 0 <= days_since_kyc_v2 <= 14

    days_since_sso = (date.today() - SSO_LAUNCH_DATE).days

    health = get_overall_health_v2(wow, device_table)
    alerts = generate_alerts_v2(
        wow, device_table, sso_pct,
        kyc_start_pct=kyc_start_pct, kyc_done_pct=kyc_done_pct,
        kyc_start_wow_pp=kyc_start_wow_pp, kyc_done_wow_pp=kyc_done_wow_pp,
        kyc_steps_wow=kyc_steps_wow,
    )
    wins   = generate_wins_v2(
        wow, device_table, sso_pct,
        kyc_start_pct=kyc_start_pct, kyc_done_pct=kyc_done_pct,
        kyc_start_wow_pp=kyc_start_wow_pp, kyc_done_wow_pp=kyc_done_wow_pp,
    )

    print(f"\n  📊 Signups:        {cur_signup:,}")
    print(f"  📧 Email method:   OTP {email_pct}% | SSO {sso_pct}%")
    print(f"  🏦 KYC:            Start {kyc_start_pct}% ({kyc_start_wow_pp:+.1f}pp WoW) | Done {kyc_done_pct}% ({kyc_done_wow_pp:+.1f}pp WoW)")
    if kyc_steps_wow:
        worst = kyc_steps_wow[0]
        print(f"  🔍 KYC worst step: {worst['label']} ({worst['wow_pp']:+.1f}pp WoW, now {worst['cur_pct']}%)")
    print(f"  🩺 Health:         {health.upper()}")

    # ── Build executive briefing ──────────────────────────────────────────
    now_ist = datetime.utcnow() + timedelta(hours=5, minutes=30)
    exec_payload = build_exec_report(
        period_label=label,
        cur_signup=cur_signup,
        wow=wow,
        prev_prev_signup=prev_prev_signup,
        yesterday_snapshot=yesterday_snapshot,
        device_table=device_table,
        sso_pct=sso_pct,
        kyc_start_pct=kyc_start_pct,
        kyc_done_pct=kyc_done_pct,
        kyc_start_wow_pp=kyc_start_wow_pp,
        kyc_done_wow_pp=kyc_done_wow_pp,
        kyc_cohort_signups=prior_signup,
        kyc_v2_recent=kyc_v2_recent,
        alerts=alerts,
        wins=wins,
        health=health,
        generated_at=now_ist.strftime("%Y-%m-%d %H:%M"),
    )

    # ── Post executive briefing ───────────────────────────────────────────
    if dry_run:
        print("\n── DRY RUN — executive briefing ─────────────────────────────────────")
        print(exec_payload["text"])
        print("────────────────────────────────────────────────────────────────────")
        return

    print("\n📤  Sending executive briefing to Slack...")
    if send_to_slack(webhook_url, exec_payload):
        print("✅  Report sent!")
    else:
        print("❌  Failed to send report to Slack")
        sys.exit(1)


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    run(dry_run=dry_run)
