#!/usr/bin/env python3
"""
Aspero Amplitude → Slack Agent
================================
Fetches 7-day rolling signup funnel data from Amplitude and posts a
narrative report to Slack generated by Claude (LLM).

Report flow:
  1. Python fetches all Amplitude data (Funnel API + Segmentation API)
  2. Python computes derived metrics (WoW deltas, device tier classification,
     Em%, PIN%, SSO adoption %, etc.)
  3. Python pre-formats the device tier table (monospace code block)
  4. Claude generates the full narrative report using the writing guide
     embedded in reporter.py as the system prompt
  5. Report is posted to Slack as plain mrkdwn text

Fallback: if Claude is unavailable (no API key, network error), the agent
falls back to the legacy Block Kit format via build_message_v2().

Funnel milestones:
  OTP          = VERIFY_OTP_SUCCESS           (new + returning users)
  Email Page   = EMAIL_PAGE_VIEW              (proxy for new-user OTPs at 99.5%)
  Email ✓ OTP  = EMAIL_VERIFY_OTP_SUCCESS     (new users only)
  Email ✓ SSO  = SSO_VERIFICATION_SUCCESS     (new users only, launched 6 Mar 2026)
  Signup ✓     = SETUP_SECURE_PIN_SUCCESS     (new users only)

API calls: 12 total
  [1–2]  Device funnel: OTP→EmailPage→Email→Signup, OTP→EmailPage→SSO→Signup (current 7d)
  [3–6]  Event totals for prior 7d (WoW comparison)
  [7–8]  Event totals for prior-prior 7d (consecutive trend detection)
  [9–12] Event totals for yesterday (daily snapshot)

Usage:
  python3 agent.py [--dry-run]

Required env vars:
  AMPLITUDE_API_KEY      Amplitude API key (Project 506002)
  AMPLITUDE_SECRET_KEY   Amplitude secret key
  SLACK_WEBHOOK_URL      Slack incoming webhook URL
  ANTHROPIC_API_KEY      Anthropic API key (for LLM report generation)
"""

import json
import os
import sys
from datetime import datetime, timedelta

from amplitude import AmplitudeClient
from config import MILESTONE_EVENTS
from insights import (
    compute_device_funnel_table,
    compute_wow_totals,
    compute_yesterday_snapshot,
    generate_alerts_v2,
    generate_wins_v2,
    get_overall_health_v2,
)
from slack import build_message_v2, send_to_slack


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _date_window(days: int, offset_days: int = 0):
    end   = datetime.now() - timedelta(days=offset_days)
    start = end - timedelta(days=days)
    return start.strftime("%Y%m%d"), end.strftime("%Y%m%d")


def _period_label(start_str: str, end_str: str) -> str:
    start = datetime.strptime(start_str, "%Y%m%d")
    end   = datetime.strptime(end_str,   "%Y%m%d")
    if start.year == end.year:
        return f"{start.strftime('%b %-d')} – {end.strftime('%-d, %Y')}"
    return f"{start.strftime('%b %-d, %Y')} – {end.strftime('%b %-d, %Y')}"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run(dry_run: bool = False):
    # ── Credentials ───────────────────────────────────────────────────────
    api_key          = os.getenv("AMPLITUDE_API_KEY")
    secret_key       = os.getenv("AMPLITUDE_SECRET_KEY")
    webhook_url      = os.getenv("SLACK_WEBHOOK_URL")
    anthropic_key    = os.getenv("ANTHROPIC_API_KEY")

    missing = [k for k, v in {
        "AMPLITUDE_API_KEY":    api_key,
        "AMPLITUDE_SECRET_KEY": secret_key,
        "SLACK_WEBHOOK_URL":    webhook_url,
    }.items() if not v]

    if missing and not dry_run:
        print(f"❌  Missing env vars: {', '.join(missing)}")
        sys.exit(1)

    client = AmplitudeClient(api_key or "", secret_key or "")

    # ── Date windows ──────────────────────────────────────────────────────
    cur_start,        cur_end        = _date_window(7)
    prev_start,       prev_end       = _date_window(7, offset_days=7)
    prev_prev_start,  prev_prev_end  = _date_window(7, offset_days=14)
    yest_str                         = (datetime.now() - timedelta(days=1)).strftime("%Y%m%d")
    label = _period_label(cur_start, cur_end)

    print(f"\n🗓  Period:          {label}  ({cur_start} → {cur_end})")
    print(f"📅  Prior period:    {prev_start} → {prev_end}")
    print(f"📅  Prior-prior:     {prev_prev_start} → {prev_prev_end}")
    print(f"📅  Yesterday:       {yest_str}")

    # ── Fetch [1–2] — current 7d funnels by device type ──────────────────
    # device_type is the correct Amplitude Funnel API group_by parameter.
    # device_family is shown in the Amplitude UI but returns empty data from
    # the Funnel API. classify_device_type() handles both marketing names
    # and raw hardware codes (SM-S901B, 2201116TG, RMX3511).
    print("\n📡  [1/12] OTP → Email Page → Email OTP → Signup funnel by device type...")
    otp_email_funnel = client.get_funnel_by_device_type(
        [MILESTONE_EVENTS["otp"], MILESTONE_EVENTS["email_page"],
         MILESTONE_EVENTS["email_otp"], MILESTONE_EVENTS["signup"]],
        cur_start, cur_end,
    )
    print(f"    device_types={len(otp_email_funnel)}")

    print("\n📡  [2/12] OTP → Email Page → Email SSO → Signup funnel by device type...")
    otp_sso_funnel = client.get_funnel_by_device_type(
        [MILESTONE_EVENTS["otp"], MILESTONE_EVENTS["email_page"],
         MILESTONE_EVENTS["email_sso"], MILESTONE_EVENTS["signup"]],
        cur_start, cur_end,
    )
    print(f"    device_types={len(otp_sso_funnel)}")

    # ── Fetch [3–6] — prior 7d totals (WoW) ──────────────────────────────
    print(f"\n📡  [3–6] Prior 7d totals ({prev_start} → {prev_end})...")
    prior_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],       prev_start, prev_end)
    prior_email  = client.get_event_totals(MILESTONE_EVENTS["email_otp"], prev_start, prev_end)
    prior_sso    = client.get_event_totals(MILESTONE_EVENTS["email_sso"], prev_start, prev_end)
    prior_signup = client.get_event_totals(MILESTONE_EVENTS["signup"],    prev_start, prev_end)
    print(f"    otp={prior_otp:,}  email_otp={prior_email:,}  email_sso={prior_sso:,}  signup={prior_signup:,}")

    # ── Fetch [7–8] — prior-prior 7d totals (consecutive trend) ──────────
    print(f"\n📡  [7–8] Prior-prior 7d totals ({prev_prev_start} → {prev_prev_end})...")
    prev_prev_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],    prev_prev_start, prev_prev_end)
    prev_prev_signup = client.get_event_totals(MILESTONE_EVENTS["signup"], prev_prev_start, prev_prev_end)
    print(f"    otp={prev_prev_otp:,}  signup={prev_prev_signup:,}")

    # ── Fetch [9–12] — yesterday snapshot ────────────────────────────────
    print(f"\n📡  [9–12] Yesterday totals ({yest_str})...")
    yest_otp    = client.get_event_totals(MILESTONE_EVENTS["otp"],       yest_str, yest_str)
    yest_email  = client.get_event_totals(MILESTONE_EVENTS["email_otp"], yest_str, yest_str)
    yest_sso    = client.get_event_totals(MILESTONE_EVENTS["email_sso"], yest_str, yest_str)
    yest_signup = client.get_event_totals(MILESTONE_EVENTS["signup"],    yest_str, yest_str)
    print(f"    otp={yest_otp:,}  email={yest_email:,}  sso={yest_sso:,}  signup={yest_signup:,}")

    # ── Compute metrics ───────────────────────────────────────────────────
    print("\n🔍  Computing metrics...")

    device_table = compute_device_funnel_table(otp_email_funnel, otp_sso_funnel)

    cur_otp         = sum(s[0] for s in otp_email_funnel.values() if s)
    cur_email_page  = sum(s[1] for s in otp_email_funnel.values() if len(s) > 1)
    cur_email       = sum(s[2] for s in otp_email_funnel.values() if len(s) > 2)
    cur_sso         = sum(s[2] for s in otp_sso_funnel.values()   if len(s) > 2)
    cur_signup      = (sum(s[3] for s in otp_email_funnel.values() if len(s) > 3) +
                       sum(s[3] for s in otp_sso_funnel.values()   if len(s) > 3))
    cur_email_total = cur_email + cur_sso

    prior_email_total = prior_email + prior_sso

    wow = compute_wow_totals(
        cur_otp, cur_email_total, cur_signup,
        prior_otp, prior_email_total, prior_signup,
    )

    yesterday_snapshot = compute_yesterday_snapshot(
        yest_otp, yest_email + yest_sso, yest_signup,
        cur_otp, cur_email_total, cur_signup,
    )

    sso_pct   = round(cur_sso   / cur_email_total * 100, 1) if cur_email_total > 0 else 0.0
    email_pct = round(cur_email / cur_email_total * 100, 1) if cur_email_total > 0 else 0.0

    health = get_overall_health_v2(wow, device_table)
    alerts = generate_alerts_v2(wow, device_table, sso_pct)
    wins   = generate_wins_v2(wow, device_table, sso_pct)

    from datetime import date
    from config import SSO_LAUNCH_DATE
    days_since_sso = (date.today() - SSO_LAUNCH_DATE).days
    days_remaining = max(0, 30 - days_since_sso)

    print(f"\n  📊 Signups:        {cur_signup:,}")
    print(f"  📧 Email method:   OTP {email_pct}% | SSO {sso_pct}%")
    print(f"  🩺 Health:         {health.upper()}")

    # ── Pre-format device table ───────────────────────────────────────────
    from slack import _milestone_table
    device_table_formatted = _milestone_table(
        device_table, cur_email_page, cur_email_total, cur_signup
    )

    # ── Build data dict for LLM reporter ─────────────────────────────────
    now_ist = datetime.utcnow() + timedelta(hours=5, minutes=30)
    data = {
        "report_date":           now_ist.strftime("%a %b %-d, %Y"),
        "period":                label,
        "cur_signup":            cur_signup,
        "cur_otp":               cur_otp,
        "cur_email_total":       cur_email_total,
        "cur_email_page":        cur_email_page,
        "cur_sso":               cur_sso,
        "sso_pct":               sso_pct,
        "wow": {
            "signup": wow.get("signup", {}),
            "otp":    wow.get("otp",    {}),
            "email":  wow.get("email",  {}),
        },
        "prior_prior": {
            "signup": prev_prev_signup,
            "otp":    prev_prev_otp,
        },
        "yesterday": {
            "signup":     yesterday_snapshot.get("registrations", {}),
            "otp":        yesterday_snapshot.get("otp_verified",  {}),
            "email_conv": yesterday_snapshot.get("email_conv",    {}),
        },
        "device_table": [
            {
                "tier":     r["tier"],
                "label":    r["label"],
                "mob_verif": r["email_page"],
                "email":    r["email_total"],
                "signup":   r["signup"],
                "em_pct":   r["newuser_to_email_pct"],
                "pin_pct":  r["email_to_signup_pct"],
            }
            for r in device_table
        ],
        "device_table_formatted":  device_table_formatted,
        "sso_available":           days_since_sso >= 0,
        "days_since_sso":          days_since_sso,
        "days_remaining_sso":      days_remaining,
        "generated_at":            now_ist.strftime("%Y-%m-%d %H:%M"),
    }

    # ── Generate report via LLM (fallback to Block Kit) ───────────────────
    if dry_run:
        print("\n── DRY RUN — data dict ──────────────────────────────────────────────")
        print(json.dumps(data, indent=2, ensure_ascii=False))
        print("────────────────────────────────────────────────────────────────────")
        return

    report_text = None
    if anthropic_key:
        try:
            print("\n🤖  Generating narrative report via Claude...")
            from reporter import generate_report
            report_text = generate_report(data)
            print("✅  LLM report generated.")
        except Exception as e:
            print(f"⚠️  LLM report failed ({e}), falling back to Block Kit format...")

    if report_text:
        payload = {"text": report_text}
    else:
        # Fallback: legacy Block Kit format
        payload = build_message_v2(
            period_label=label,
            device_table=device_table,
            cur_otp=cur_otp,
            cur_email_page=cur_email_page,
            cur_email_otp=cur_email,
            cur_email_sso=cur_sso,
            cur_signup=cur_signup,
            wow=wow,
            yesterday_snapshot=yesterday_snapshot,
            alerts=alerts,
            wins=wins,
            health=health,
        )

    print("\n📤  Sending to Slack...")
    if send_to_slack(webhook_url, payload):
        print("✅  Report sent!")
    else:
        print("❌  Failed to send to Slack")
        sys.exit(1)


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    run(dry_run=dry_run)
